from enum import Enum


class MemberStatus(Enum):
    NOT_PROCESSED = 0
    ADDED_TO_GROUP = 1
    SKIPPED_PRIVACY = 2
    SKIPPED_HAS_LEFT = 3
    SKIPPED_ADDER_RESTRICTED = 4
    SKIPPED_PEER_INVALID = 5
    SKIPPED_ALREADY_MEMBER = 6
    SKIPPED_HAVE_NOT_USERNAME = 7
    SKIPPED_NO_MESSAGE_RIGHTS = 8
    SKIPPED_NO_ADMIN_RIGHTS = 9
    SKIPPED_OTHER_REASONS = 10
